### ISSUE TITLE
Request to use "node-informixdb" for the Informix connector rather "node-ibm_db"

### ISSUE THREAD

**Issue by rhtpandeyIN** [strongloop/loopback-connector-informix#58]
# Description/Steps to reproduce
Request to use "node-informixdb" for the Informix connector rather "node-ibm_db"

# Link to reproduction sandbox
this module's package.json contains below dependencies:
 "dependencies": {
    "async": "^1.5.0",
    "debug": "^3.1.0",
    "loopback-connector": "^4.0.0",
    **"loopback-ibmdb": "^2.0.0",**
    "strong-globalize": "^4.1.1"
  },

**loopback-ibmdb** has the below dependencies:
"dependencies": {
    "async": "^2.6.1",
    "debug": "^3.1.0",
    **"ibm_db": "^2.3.0",**
    "loopback-connector": "^4.0.0",
    "strong-globalize": "^4.0.0"
  },

**ibm_db** is the designated connector for Db2 database and has limited support for Informix database.

ibm_db [https://github.com/ibmdb/node-ibm_db] uses DRDA protocol to connect with the Informix whereas "informixdb" [https://github.com/OpenInformix/node-informixdb] uses the SQLI protocol which is native to the Informix Database.

I know all this because I have been part of Db2 node.js driver (node-ibm_db) [https://github.com/ibmdb/node-ibm_db/graphs/contributors] and now I am an active contributor to the Informix database connector.

# Expected result

To pursue this change you will have to change the dependency in the loopback-ibmdb module:

from this :
"dependencies": {
    "async": "^2.6.1",
    "debug": "^3.1.0",
    **"ibm_db": "^2.3.0",**
    "loopback-connector": "^4.0.0",
    "strong-globalize": "^4.0.0"
  },

to this:
"dependencies": {
    "async": "^2.6.1",
    "debug": "^3.1.0",
    **"informixdb": "^2.1.0",**
    "loopback-connector": "^4.0.0",
    "strong-globalize": "^4.0.0"
  },

and will have to change some code in the both "loopback-connector-informix" and "loopback-ibmdb" modules.
These changes are not that significant (just a few lines changes) and the existing code will work like magic.
So, please let me know if you think this request has some weight. The only thing that concerns me is Informix does not provide the latest support for DRDA layer and ibm_db would be missing a major part of Informix features (for future developments as well).

# Additional information
node-informixdb : https://github.com/OpenInformix/node-informixdb
node-ibmdb : https://github.com/ibmdb/node-ibm_db/

and the best part is their codebase is almost the same, so loopback existing code will work without much effort.

**Comment by rhtpandeyIN** [comment]
BTW, I have the required code changes for this transition. If you are interested then let me know, I would love to share my findings.

**Comment by rhtpandeyIN** [comment]
Hi team, any updates?

**Comment by bajtos** [comment]
Closing in favor of https://github.com/strongloop/loopback/issues/4342
